MODELS_DIR = "../models"
LOGS_DIR = "../logs"
PRETRAINED_PATH = f"{MODELS_DIR}/pretrainedFrozenLakeDQN"
TRANSERED_PATH = f"{MODELS_DIR}/transferedFrozenLakeDQN"
NON_TRANSERED_PATH = f"{MODELS_DIR}/nonTransferedFrozenLakeDQN"